version: "3.8"

services:

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  adoption-service:
    build: ./backend-app/animal-adoption-backend
    container_name: adoption_service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/animal_adoption
      - SECRET_KEY=cheiasecreta
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  analytics-service:
    build: ./backend-app/analytics-service
    container_name: analytics_service
    ports:
      - "5002:5002"
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/analytics
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
      - PORT=5002
    depends_on:
      - rabbitmq
      - kafka
      - zookeeper
      - mongodb

  notifications-service:
    build: ./backend-app/notification-service
    container_name: notifications_service
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
    depends_on:
      - rabbitmq


  adoption-mfe:
    build: ./frontend-app/adoption
    container_name: adoption_mfe
    ports:
      - "9002:80"  

  notifications-mfe:
    build: ./frontend-app/notifications
    container_name: notifications_mfe
    ports:
      - "9003:80"

  analytics-mfe:
    build: ./frontend-app/analytics
    container_name: analytics_mfe
    ports:
      - "9001:80"

  container-mfe:
    build: ./frontend-app/main-app
    container_name: main_mfe
    ports:
      - "9000:80"
